### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by DMClVG** [dumbluckarts/not-quake#1]
I've tried this out for a bit and I have to say it looks kinda interesting, although unfortunately I have no knowledge of what it is meant to be as it lacks a description or any sort of README file in its repository. I think a rough explanation would be highly appreciated

**Comment by nelsondev** [comment]
Hi DMCIVG, we're currently in early alpha. We didn't expect anyone to see this project yet and take interest. Stand by for a more polished build.
